baseURL = ""
languageCode = "en-us"
theme = "projects-theme"
title = "Harvester - Open-source hyperconverged infrastructure"

pluralizeListTitles = false
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableGitInfo = true
googleAnalytics = 'UA-56382716-11'

[blackfriday]
fractions = false
#hrefTargetBlank = true

[outputFormats.Algolia]
baseName = "algolia"
isPlaintext = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[params]
# rename when the logo is updated, so we indirectly also invalidate caches
logo = "images/logo_horizontal.svg"
description= "An open-source hyperconverged infrastructure (HCI) software for a cloud-native world"
githubLink = "https://github.com/harvester/harvester"
docsLink = "https://docs.harvesterhci.io"
css = ["css/custom.css", "styles-bundle-369.css"]
favicon = "images/favicon.ico"
  github = "https://github.com/harvester/harvester"

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    
[menu]

  [[menu.main]]
    identifier = "docs"
    name = "DOCS"
    url = "https://docs.harvesterhci.io"
    weight = -110
    
